### PR TITLE
Add more nodetypes, use table for nodetypes, don't use globals

### PR DESCRIPTION
**Pull request by dchinmay2**

### CODE REVIEW

**Comment by p00f** [comment]
There is no `array.contains` in lua, if I used an array-like table I'd have to iterate through it to check if it contains the nodetype. So I used a hashmap-like table

**Comment by dchinmay2** [comment]
`vim.tbl_contains` iterates through the table so using a key-value table is faster (when the list becomes bigger)

https://github.com/neovim/neovim/blob/1186f7dd96b054d6a653685089fc845a8f5d2f27/runtime/lua/vim/shared.lua#L182

**Comment by haringsrob** [comment]
Hey @p00f,

Thanks a lot, in https://github.com/haringsrob/nvim_context_vt/pull/1 vim.tbl_find is used for matching which I like a little bit more.

Also some of the types are already there now, could you update with the types you miss and apply it to that table?

**Comment by dchinmay2** [comment]
Ok

**Comment by dchinmay2** [comment]
Done

**Comment by tamago324** [comment]
@p00f I think you need to add the types (`function_defintion` and `local_function`) that you were adding to the table in [this commit](https://github.com/haringsrob/nvim_context_vt/pull/2/commits/a64ef956e6f09d6f259c99c5a7f3da79265cdf47). What do you think?

**Comment by dchinmay2** [comment]
Oh yes I fixed the merge conflict on github and messed up.

**Comment by dchinmay2** [comment]
Are you open to adding loops?

**Comment by haringsrob** [comment]
As in target? Everything that has spans multiple lines can be enabled I guess

**Comment by dchinmay2** [comment]
I'll do loops later, my fork is messy

**Comment by haringsrob** [comment]
For and while loops are in #3 I think, if you still need more just let me know :) 
Thanks a lot

**Comment by tamago324** [comment]
@p00f Please let me know if I'm wrong.
Does `function_defintion` mean `function_definition`?
Or is there a node name called `function_defintion`?
In c-tree-sitter, there was `function_definition`, but not `function_defintion`.

**Comment by tamago324** [comment]
Fixed in [this commit](https://github.com/haringsrob/nvim_context_vt/pull/4/commits/d2459a3e29c0e5e8c61104899aa73f7d410ad337). If you have any problems, please reply.

**Comment by dchinmay2** [comment]
Yeah typo it should be `function_definition`

**Pull request merged**
