### PR TITLE
Add typescript and function arguments support.

### PR DESCRIPTION
**Pull request by ghost**
This PR will add vt context support for function argument, interface and enum.

### CODE REVIEW

**Comment by haringsrob** [comment]
Hey, I can merge if you fix the indentation :).

Thank you!

**Comment by ghost** [comment]
> Hey, I can merge if you fix the indentation :).
> 
> Thank you!

What? But I didn't find any problems with it!!
Please tell me what went wrong.(It's best to have screenshots)
Thanks!

**Comment by haringsrob** [comment]
You can see it here: https://github.com/haringsrob/nvim_context_vt/blob/9d32d1368159eba8d0bcc35317806e96a3dd9dcc/lua/nvim_context_vt.lua

**Comment by ghost** [comment]
That's OK.

**Comment by haringsrob** [comment]
Screenshot 2021-07-23 at 08 05 43

I think you have used tabs instead of spaces.

**Comment by ghost** [comment]
> Screenshot 2021-07-23 at 08 05 43
> 
> 我认为您使用了选项卡而不是空格。

Yes, fix it.

**Pull request merged**
